name: Bug report
description: Create a bug report
title: "[BUG] "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug! Please fill out the required fields.

  - type: checkboxes
    id: latest
    attributes:
      label: "Version confirmation"
      options:
        - label: "I confirm I’m using the latest version of this tool."
          required: true

  - type: checkboxes
    id: latest_gate
    attributes:
      label: "Required before submitting"
      description: "Issues may be closed if they don’t meet this requirement."
      options:
        - label: "I acknowledge that reports from non-latest versions may be closed without further investigation."
          required: true

  - type: dropdown
    id: googled
    attributes:
      label: "Did you try googling any error messages?"
      options:
      - "No"
      - "Yes"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "What happened?"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "It should..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      description: "A clear and concise description of what actually happened."
      placeholder: "It did..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Be specific—exact clicks/commands."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      render: text
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots / logs (paste only)"
      description: "Paste short logs here. For large logs or files, submit the issue first, then upload attachments in a comment."
      placeholder: "Paste a short excerpt here. Attach the full file after submitting."
      render: text
    validations:
      required: false

  - type: dropdown
    id: zorin_version
    attributes:
      label: "Zorin OS version"
      description: "Which version are you on?"
      options:
        - "16 Core"
        - "16.1 Core"
        - "16.2 Core"
        - "16.3 Core"
        - "17 Core"
        - "17.1 Core"
        - "17.2 Core"
        - "17.3 Core"
#         - "18 Core"
#         - "18.1 Core"
#         - "18.2 Core"
#         - "18.3 Core"
        - "Beta release"
        - "Other / Unsure"
    validations:
      required: true

  - type: input
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      placeholder: "Anything else maintainers should know?"
    validations:
      required: false
